programs = pcb2ver bin2m bin2raw drop1 bin2hex byte2hex msg2hex lut2hex hex2bin  

all: $(programs)
	cp $(programs) ../bin

pcb2ver:

bin2m:

bin2raw:

drop1:

bin2hex:

byte2hex:

msg2hex:

lut2hex:

hex2bin:

