all: sdram_bank0.hex sdram_bank1.hex sdram_bank2.hex sdram_bank3.hex


sdram_bank0.hex: randhex.py
	randhex.py > sdram_bank0.hex

sdram_bank1.hex: randhex.py
	randhex.py > sdram_bank1.hex

sdram_bank2.hex: randhex.py
	randhex.py > sdram_bank2.hex

sdram_bank3.hex: randhex.py
	randhex.py > sdram_bank3.hex
